import { defineEndpoint, UsageModelKind } from "@shared/core";
import { zContractModel } from "../../schema/common.ts";
import { zCompareBody } from "./schema/inputs.ts";

export default defineEndpoint({
    meta: {
        displayName: "deepface.dev Vector Comparison",
        summary: "Compare exactly two existing facial embeddings.",
        description:
            "Compare one source vector with one target vector, generated by " +
            "the same model. Returns distance and, when available, the match " +
            "decision. The vectors must have equal dimensions matching the " +
            "selected model. This endpoint never generates an embedding: " +
            "use represent first if you have images.",
        categories: ["face-verification"],
        notes: [
            "monid_v1: 0.044 credits per successful call, including non-matches; non-2xx responses cost zero.",
            "Synchronous vector-to-vector only: image comparison, multiple targets, batching, and async mode are excluded from this tariff.",
        ],
    },
    request: { method: "POST", path: "/compare" },
    input: {
        schema: {
            body: zCompareBody.pick({
                model_name: true,
                source_vector: true,
                target_vector: true,
                distance_metric: true,
                threshold: true,
            }).extend({
                model_name: zContractModel,
                source_vector: zCompareBody.shape.source_vector.unwrap().min(1)
                    .max(512),
                target_vector: zCompareBody.shape.target_vector.unwrap().min(1)
                    .max(512),
                distance_metric: zCompareBody.shape.distance_metric.unwrap()
                    .default("cosine"),
            }).strict(),
        },
    },
    usage: {
        model: {
            kind: UsageModelKind.PER_CALL,
            consumes: { credit: "default", amount: 0.044 },
        },
    },
});
