import { z } from "zod";
import {
    markdownOptionFields,
    zScrapeMaxAgeMs,
    zTimeoutOpts,
    zWaitForMs,
} from "../../../schema/common.ts";

/** POST /web/search body — the vendor mirror
 *  (docs.context.dev/api-reference/web-scraping/search, 2026-09-17). */
export const zSearchBody = z.object({
    query: z.string().min(1).max(500).describe(
        "Search query. Accepts natural language as well as Google-style " +
            "operators: site:, -site:, inurl:, intitle:, quoted phrases, OR.",
    ),
    numResults: z.number().int().min(10).max(100).describe(
        "Number of results to request and return (10-100). Default 10. " +
            "Sizes the hold: one credit per 10 results.",
    ).optional(),
    includeDomains: z.array(z.string()).describe(
        "Allowlist — only return results from these domains.",
    ).optional(),
    excludeDomains: z.array(z.string()).describe(
        "Blocklist — drop results from these domains.",
    ).optional(),
    freshness: z.enum([
        "last_24_hours",
        "last_week",
        "last_month",
        "last_year",
    ]).describe(
        "Restrict results to content published within this window.",
    ).optional(),
    country: z.enum([
        "af",
        "al",
        "dz",
        "as",
        "ad",
        "ao",
        "ai",
        "aq",
        "ag",
        "ar",
        "am",
        "aw",
        "au",
        "at",
        "az",
        "bs",
        "bh",
        "bd",
        "bb",
        "by",
        "be",
        "bz",
        "bj",
        "bm",
        "bt",
        "bo",
        "ba",
        "bw",
        "bv",
        "br",
        "io",
        "bn",
        "bg",
        "bf",
        "bi",
        "kh",
        "cm",
        "ca",
        "cv",
        "ky",
        "cf",
        "td",
        "cl",
        "cn",
        "cx",
        "cc",
        "co",
        "km",
        "cg",
        "cd",
        "ck",
        "cr",
        "ci",
        "hr",
        "cu",
        "cy",
        "cz",
        "dk",
        "dj",
        "dm",
        "do",
        "ec",
        "eg",
        "sv",
        "gq",
        "er",
        "ee",
        "et",
        "fk",
        "fo",
        "fj",
        "fi",
        "fr",
        "gf",
        "pf",
        "tf",
        "ga",
        "gm",
        "ge",
        "de",
        "gh",
        "gi",
        "gr",
        "gl",
        "gd",
        "gp",
        "gu",
        "gt",
        "gn",
        "gw",
        "gy",
        "ht",
        "hm",
        "va",
        "hn",
        "hk",
        "hu",
        "is",
        "in",
        "id",
        "ir",
        "iq",
        "ie",
        "il",
        "it",
        "jm",
        "jp",
        "jo",
        "kz",
        "ke",
        "ki",
        "kp",
        "kr",
        "kw",
        "kg",
        "la",
        "lv",
        "lb",
        "ls",
        "lr",
        "ly",
        "li",
        "lt",
        "lu",
        "mo",
        "mk",
        "mg",
        "mw",
        "my",
        "mv",
        "ml",
        "mt",
        "mh",
        "mq",
        "mr",
        "mu",
        "yt",
        "mx",
        "fm",
        "md",
        "mc",
        "mn",
        "ms",
        "ma",
        "mz",
        "mm",
        "na",
        "nr",
        "np",
        "nl",
        "an",
        "nc",
        "nz",
        "ni",
        "ne",
        "ng",
        "nu",
        "nf",
        "mp",
        "no",
        "om",
        "pk",
        "pw",
        "ps",
        "pa",
        "pg",
        "py",
        "pe",
        "ph",
        "pn",
        "pl",
        "pt",
        "pr",
        "qa",
        "re",
        "ro",
        "ru",
        "rw",
        "sh",
        "kn",
        "lc",
        "pm",
        "vc",
        "ws",
        "sm",
        "st",
        "sa",
        "sn",
        "rs",
        "sc",
        "sl",
        "sg",
        "sk",
        "si",
        "sb",
        "so",
        "za",
        "gs",
        "es",
        "lk",
        "sd",
        "sr",
        "sj",
        "sz",
        "se",
        "ch",
        "sy",
        "tw",
        "tj",
        "tz",
        "th",
        "tl",
        "tg",
        "tk",
        "to",
        "tt",
        "tn",
        "tr",
        "tm",
        "tc",
        "tv",
        "ug",
        "ua",
        "ae",
        "gb",
        "us",
        "um",
        "uy",
        "uz",
        "vu",
        "ve",
        "vn",
        "vg",
        "vi",
        "wf",
        "eh",
        "ye",
        "zm",
        "zw",
    ]).describe(
        "Two-letter ISO 3166-1 alpha-2 country code, lowercase, to localize " +
            "results to (e.g. 'us', 'gb', 'de').",
    ).optional(),
    queryFanout: z.boolean().describe(
        "Expand the query into parallel variants for broader recall.",
    ).optional(),
    markdownOptions: z.object({
        enabled: z.boolean().describe(
            "Scrape each result to Markdown in the same call. Off by default " +
                "to keep search cheap and fast; enabling it consumes additional " +
                "scrape credits.",
        ).optional(),
        includeLinks: markdownOptionFields.includeLinks.optional(),
        includeImages: markdownOptionFields.includeImages.optional(),
        shortenBase64Images: markdownOptionFields.shortenBase64Images
            .optional(),
        useMainContentOnly: markdownOptionFields.useMainContentOnly.optional(),
        pdf: z.object({
            shouldParse: z.boolean().describe(
                "Parse PDF results. When false, PDF results are skipped. " +
                    "Default true.",
            ).optional(),
            start: z.number().int().min(1).describe(
                "First 1-based PDF page to parse.",
            ).optional(),
            end: z.number().int().min(1).describe(
                "Last 1-based PDF page to parse. Must be >= start.",
            ).optional(),
        }).strict().describe("PDF handling for scraped results.").optional(),
        includeFrames: markdownOptionFields.includeFrames.optional(),
        maxAgeMs: zScrapeMaxAgeMs.optional(),
        waitForMs: zWaitForMs.optional(),
        timeoutOpts: zTimeoutOpts.optional(),
    }).strict().describe(
        "Inline Markdown scraping for each result. Set enabled: true to " +
            "activate.",
    ).optional(),
    timeoutOpts: zTimeoutOpts.optional(),
}).strict();
