import { defineEndpoint, UsageModelKind } from "@shared/core";
import { z } from "zod";
import { zContractImage, zContractModel } from "../../schema/common.ts";
import { zRepresentBody } from "./schema/inputs.ts";

export default defineEndpoint({
    meta: {
        displayName: "deepface.dev Face Embedding",
        summary: "Generate facial embeddings from one consented image.",
        description:
            "Submit one base64 image and an explicit model to receive facial " +
            "embeddings and detected face regions. Preserve the model name " +
            "with each vector; only compare embeddings generated by the same " +
            "model. For two images, use verify; for stored vectors, use compare.",
        categories: ["embeddings"],
        notes: [
            "monid_v1: 1.02 credits per successful call; non-2xx responses cost zero.",
        ],
    },
    request: { method: "POST", path: "/represent" },
    input: {
        schema: {
            body: zRepresentBody.extend({
                img: zContractImage,
                model_name: zContractModel,
                detector_backend: z.literal("opencv").default("opencv"),
                enforce_detection: z.literal(true).default(true),
                align: z.literal(true).default(true),
                normalization: z.literal("base").default("base"),
            }).strict(),
        },
    },
    usage: {
        model: {
            kind: UsageModelKind.PER_CALL,
            consumes: { credit: "default", amount: 1.02 },
        },
    },
});
